version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/rsletten/portainer/data:/data
      - /home/rsletten/portainer/shared:/shared
    environment:
      - TZ=Americas/New_York
